### ISSUE TITLE
Mac os x (lion) - Emacs 24.0.90 - unable to use Emacs-Starter

### ISSUE THREAD

**Issue by bartlomiejdanek** [technomancy/emacs-starter-kit#103]
I try to install from http://bandwidth.porkrind.org/emacs-builds/Emacs-pretest-24.0.90-universal-10.6.7.dmg and brew

```
brew install emacs --cocoa --use-git-head --HEAD
```

I had the error after install stater-kit

```
Symbol's function definition is void: mapcan
```

**Comment by shoaibkamil** [comment]
This seems to be caused by emacs24 recently removing mapcan.  I'm not sure whether this removal is intended to be permanent or not.

I was able to get everything to work by replacing the definition of `ido-ubiquitous--set-difference` with:

```
(defun ido-ubiquitous--set-difference (list1 list2)
  "Replacement for `set-difference' from `cl'."
   (apply #'nconc  (mapcar (lambda (elt) (unless (memq elt list2) (list elt)))
          list1)))
```

That is, by replacing mapcan with mapcar followed by applying nconc.

**Comment by bartlomiejdanek** [comment]
thanks! works :)

**Comment by DarwinAwardWinner** [comment]
I fixed my ido-ubiquitous package. mapcan is actually defined in the cl package in Emacs, which I was trying to eliminate from ido-ubiquitous. I eliminated another cl function, but I used mapcan instead, since I thought it was built-in. Ido-ubiquitous version 0.6 should not require any cl functions, so it should work fine now.

**Comment by mamciek** [comment]
It still doesn't work with the newest  ido-ubiquitous

Related: https://github.com/technomancy/ido-ubiquitous/issues/10

**Comment by DarwinAwardWinner** [comment]
The newest ido-ubiquitous on Marmalade is version 1.0, which does not use mapcan at all. 

http://marmalade-repo.org/packages/ido-ubiquitous-1.0.el
